version: '3.8'

services:
  mmseg:
    image: mmsegmentation
    container_name: mmseg_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '8gb'
    volumes:
      - ./data:/mmsegmentation/data
    stdin_open: true
    tty: true
